spring.application.name=microservicios

# Jwt Configuration
# ${JWT_SECRET} and create .env file
JWT_SECRET=+b3HrU+lwRU59cmQWeEkDAL+WcxVfHKJKid16dPocsU2PwXa+OtWJHPFNYMtMGLh+/1gxmQ6T9LK4C78ELrJWw==

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=DEBUG

# Datasource settings
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.error.include-message=always